version: '3.6'
services:
  postgres:
    image: postgres:12
    restart: always
    volumes:
    - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  graphql-engine:
    image: hasura/graphql-engine:v1.3.0
    ports:
    - "${HASURA_PORT}:8080"
    depends_on:
    - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:${POSTGRES_PASSWORD}@postgres:5432/postgres
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: "false"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to set an admin secret
      HASURA_GRAPHQL_ADMIN_SECRET: "${HASURA_ADMIN_SECRET}"

      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: anonymous
      HASURA_ACTION_BASE_URL: http://backend:${BACKEND_INTERNAL_PORT}
      HASURA_WEBHOOK_NOTIFY_URL: http://backend:${BACKEND_INTERNAL_PORT}/profile/notify
      HASURA_WEBHOOK_PUBLISH_URL: http://backend:${BACKEND_INTERNAL_PORT}/profile/publish
  backend:
    build:
        context: ./backend
        dockerfile: Dockerfile.prod
    restart: always
    environment:
        - NODE_ENV=production

        # backend is not public, always make the requests internally
        - HASURA_ENDPOINT=http://graphql-engine:8080/v1/graphql
        - HASURA_ADMIN_SECRET=${HASURA_ADMIN_SECRET}
        - SLACK_WEBHOOK_URL=${SLACK_WEBHOOK_URL}
        - PORT=${BACKEND_INTERNAL_PORT}
volumes:
  db_data: